#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Bulk Rename Py
# © 2026–present Codemorra (Christopher Kranz)
# Licensed under the MIT License (see LICENSE file)

import sys

sys.path.insert(0, "/usr/lib/bulk-rename-py")

import main

if __name__ == "__main__":
    main.main()
