#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Bulk Rename Py
# © 2026–present Codemorra
# Licensed under the MIT License (see LICENSE file)

import sys

sys.path.insert(0, "/usr/lib/bulk-rename-py")

import bulk_rename_py

if __name__ == "__main__":
    bulk_rename_py.main()
